#################################################################################################
# a collection of recurring typo and short cut created quickly created vie the new_typo command #
#################################################################################################

alias 'gti'='git'
alias 'pyhton3'='python3'
alias 'pyhton'='python'
alias 'l$'='l'
alias 'eos'='oes'
alias 'ose'='oes'
alias 'eaz'='eza'
alias 'exiit'='exit'
alias 'za'='eza'
alias 'oe'='oes'
alias 'runbit'='runbot'
alias 'pqsl_seg_fault_fixer'='psql_seg_fault_fixer'
alias 'eso'='oes'
alias 'new_ypo'='new_typo'
alias 'whicj'='which'
alias 'exit$'='exit'
alias 'hotp'='htop'
alias 'pl$'='pl'
alias 'exiy'='exit'
alias 'exitt'='exit'
alias 'tgi'='tig'
alias 'cl'='clear'
alias 'tig$'='tig'
alias 'new_ytpo'='new_typo'
alias 'exirt'='exit'
alias 'new_tupo'='new_typo'
alias 'clera'='clear'
alias 'clea'='clear'
