#################################################################################################
###### a collection of recurring typo created quickly created via the new_typo command ##########
#################################################################################################

alias 'gti'='git'
alias 'pyhton3'='python3'
alias 'pyhton'='python'
alias 'l$'='l'
alias 'runbit'='runbot'
alias 'pqsl_seg_fault_fixer'='psql_seg_fault_fixer'
alias 'whicj'='which'
alias 'hotp'='htop'
alias 'pl$'='pl'
alias 'tgi'='tig'
alias 'tig$'='tig'
alias 'tog'='tig'
alias 'eos'='oes'
alias 'ose'='oes'
alias 'oe'='oes'
alias 'eso'='oes'
alias 'eaz'='eza'
alias 'za'='eza'
alias 'ez'='eza'
alias 'exiit'='exit'
alias 'exit$'='exit'
alias 'exiy'='exit'
alias 'exitt'='exit'
alias 'exirt'='exit'
alias 'clera'='clear'
alias 'clea'='clear'
alias 'cleare'='clear'
alias 'cleazr'='clear'
alias 'new_ypo'='new_typo'
alias 'new_tupo'='new_typo'
alias 'new_ytpo'='new_typo'
