local tb = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', tb.find_files, {})
vim.keymap.set('n', '<leader>fg', tb.live_grep, {})
-- vim.keymap.set('n', '<leader>fb', tb.buffers, {})
-- vim.keymap.set('n', '<leader>fh', tb.help_tags, {})
