#!/usr/bin/python3
import inspect
import types
import os

from odoo_alias import (
    CALLABLE_FROM_SHELL,
    SHELL_END_HOOK,
    SHELL_DIFFERED_COMMANDS_FILE,
    typo_alias_list,
)

shell_function_template = """{fname}() {{
    $AP/python_scripts/odoo_alias.py {fname} $@\
    {diff_exec}
}}
"""
differed_execution_code = f"""
    while read l; do
        eval $l;
    done <{SHELL_DIFFERED_COMMANDS_FILE}
    date >> $AP/differed_commands_history.txt
    cat {SHELL_DIFFERED_COMMANDS_FILE} >> $AP/differed_commands_history.txt
    cp /dev/null {SHELL_DIFFERED_COMMANDS_FILE}
"""

aliases = []
for fname in CALLABLE_FROM_SHELL:
    diff_exec = differed_execution_code if fname in SHELL_END_HOOK else ""
    aliases.append(shell_function_template.format(fname=fname, diff_exec=diff_exec))

aliases += typo_alias_list

# path to the automatically generated scripts
auto_script_path = f"{os.getenv('AP')}/autogenerated_scripts.sh"
with open(auto_script_path, "w") as f:
    for a in aliases:
        f.write(a)
